import Gallery from "@/components/Gallery";
import React from "react";
import {ImageItem} from "../page";

//for now it only loads when all images are correct
//TODO make it load even if some pictures do not load
const page = () => {
  const images: ImageItem[] = [
    {
      src: "/img/PC/hpPavillion-15s.png",
      responsive: "/img/PC/hpPavillion-15s.png",
      thumb: "/img/PC/hpPavillion-15s.png",
      alt: "HP Pavillion 15s",
      description: "AMD Ryzen™ 5 5500U (up to 4.0 GHz max boost clock, 8 MB L3 cache, 6 cores, 12 threads). 3 8 GB DDR4 3200 DIMM Storage capacity: 256 GB SSD",
      price: "4999.99",
      subHtml: `...`,
    },
    {
      src: "/img/PC/p15s.jpg",
      responsive: "/img/PC/p15s.jpg",
      thumb: "/img/PC/p15s.jpg",
      alt: "Lenovo ThinkPad E14",
      description: "Intel Core i7-1355U processor, 16GB of RAM, 512GB SSD, 14-inch IPS display, Intel Iris Xe graphics.",
      price: "1499.99",
      subHtml: `...`,
    },
    {
      src: "/img/PC/014-hp-spectre-x360-14.webp",
      responsive: "/img/PC/014-hp-spectre-x360-14.webp",
      thumb: "/img/PC/014-hp-spectre-x360-14.webp",
      alt: "HP Spectre x360",
      description: '15.6" Professional Laptop, Intel i7, 32GB RAM, 1TB SSD, NVIDIA Graphics',
      price: "1499.99",
      subHtml: `...`,
    },
    {
      src: "/img/PC/3.jpg",
      responsive: "/img/PC/3.jpg",
      thumb: "/img/PC/3.jpg",
      alt: "Desktop Workstation",
      description: "Lenovo ThinkStation P358 30GL0051US Workstation - AMD Ryzen 9 PRO 5945 - 32 GB",
      price: "3,785.93",
      subHtml: `...`,
    },
    {
      src: "/img/cctv/3.png",
      responsive: "/img/cctv/3.png",
      thumb: "/img/cctv/3.png",
      alt: "CCTV Camera",
      description: "Hikvision CCTV Camera Systems",
      price: "",
      subHtml: `...`,
    },
    {
      src: "/img/cctv/5.webp",
      responsive: "/img/cctv/5.webp",
      thumb: "/img/cctv/5.webp",
      alt: "Surveillance System",
      description: "Hikvision CCTV Camera Systems",
      price: "799.99",
      subHtml: `...`,
    },
    {
      src: "/img/bio/1.webp",
      responsive: "/img/bio/1.webp",
      thumb: "/img/bio/1.webp",
      alt: "Biometric Scanner",
      description: "Multi-Modal Biometric Access Control System with Fingerprint",
      price: "599.99",
      subHtml: `...`,
    },
    {
      src: "/img/G60F-GNSS-SPECS-800x800.png",
      responsive: "/img/G60F-GNSS-SPECS-800x800.png",
      thumb: "/img/G60F-GNSS-SPECS-800x800.png",
      alt: "HugeRock G60 Mobile Mappers",
      description: `High-precision GNSS/RTK positioning boards, support BDS, GPS, GALILEO, GLONASS, NavIC*, QZSS* systems and SBAS*, IMU* `,
      price: "3499.99",
      subHtml: `...`,
    },
    {
      src: "/img/Mapper_page0_image.png",
      responsive: "/img/Mapper_page0_image.png",
      thumb: "/img/Mapper_page0_image.png",
      alt: "Mobile Mappers",
      description: "Professional GPS Mapping System with GIS Software, Real-time Data Collection",
      price: "4999.99",
      subHtml: `...`,
    },
    {
      src: "/img/maize-dryer.jpg",
      responsive: "/img/maize-dryer.jpg",
      thumb: "/img/maize-dryer.jpg",
      alt: " Portable Multi Grain Dryer",
      description: `2T/hour portable multi grain dryer (mobile with tyres, combined diesel drier from drier discharge outlet, directly to hopper of automatic packaging and bagging scale with bagging hopper 1T size) `,
      price: "4999.99",
      subHtml: `...`,
    },
    {
      src: "/img/net/server-poweredge-r760-black-gallery-1.avif",
      responsive: "/img/net/server-poweredge-r760-black-gallery-1.avif",
      thumb: "/img/net/server-poweredge-r760-black-gallery-1.avif",
      alt: "PowerEdge R760 Rack Server",
      description: "The 2U, 2 socket Dell PowerEdge R760 enables faster time to value with peak compute performance, through optimum configurations.",
      price: "1899.99",
      subHtml: `...`,
    },
    {
      src: "/img/net/6.jpg",
      responsive: "/img/net/6.jpg",
      thumb: "/img/net/6.jpg",
      alt: "Ubiquiti Unifi Switch",
      description: "Ubiquiti Unifi Network Switches of different configurations",
      price: "1299.99",
      subHtml: `...`,
    },
    {
      src: "/img/net/cisco-isr4331-k9-front.jpg",
      responsive: "/img/net/cisco-isr4331-k9-front.jpg",
      thumb: "/img/net/cisco-isr4331-k9-front.jpg",
      alt: "ISR4331 K9 Cisco Integrated Services Router",
      description: "ISR4331 K9 provides 100 Mbps to 300 Mbps of aggregate throughput and offers an enhanced service module (SM-X) slot that supports single-width and double-width service modules, which provides flexibility in network deployment.",
      price: "4999.99",
      subHtml: `...`,
    },
    {
      src: "/img/net/c9200I-cisco-network-switch.jpg",
      responsive: "/img/net/c9200I-cisco-network-switch.jpg",
      thumb: "/img/net/c9200I-cisco-network-switch.jpg",
      alt: "Cisco c9200l Network Switch",
      description: "Catalyst C9200 Cisco Network Switches of various configuraions",
      price: "4999.99",
      subHtml: `...`,
    },
    {
      src: "/img/net/unifi 6 long range.png",
      responsive: "/img/net/unifi 6 long range.png",
      thumb: "/img/net/unifi 6 long range.png",
      alt: "Unifi 6 Long Range Access Point",
      description: "Ceiling-mounted WiFi 6 AP with 8 spatial streams and extended signal range",
      price: "4999.99",
      subHtml: `...`,
    },
    {
      src: "/img/net/Cisco_Catalyst-C8200-1N-4T-Front-scaled-640x450.webp",
      responsive: "/img/net/Cisco_Catalyst-C8200-1N-4T-Front-scaled-640x450.webp",
      thumb: "/img/net/Cisco_Catalyst-C8200-1N-4T-Front-scaled-640x450.webp",
      alt: "Cisco Catalyst 8200 Series Edge Platforms",
      description: "The Cisco® Catalyst® 8000 Edge Platforms Family provides a flexible, scalable, and secure WAN edge for business-first resiliency and cloud-native agilitys",
      price: "4999.99",
      subHtml: `...`,
    },
    {
      src: "/img/net/flexbox_with_fmp_attached_2.webp",
      responsive: "/img/net/flexbox_with_fmp_attached_2.webp",
      thumb: "/img/net/flexbox_with_fmp_attached_2.webp",
      alt: "Flexbox Series - Universal Transceivers",
      description: "Including the NEW FLEXBOX MOBILITY PACK providing Bluetooth, Battery Pack + USB-C. ",
      price: "4999.99",
      subHtml: `...`,
    },
    {
      src: "/img/net/Interactive Flipboard.jpg",
      responsive: "/img/net/Interactive Flipboard.jpg",
      thumb: "/img/net/Interactive Flipboard.jpg",
      alt: "Interactive Flipboards",
      description: "Smart interactive digital flipboards",
      price: "4999.99",
      subHtml: `...`,
    },
    {
      src: "/img/solar/led-bulbs.jpg",
      responsive: "/img/solar/led-bulbs.jpg",
      thumb: "/img/solar/led-bulbs.jpg",
      alt: "Led Bulbs",
      description: "Led Bulbs of different types",
      price: "4999.99",
      subHtml: `...`,
    },
    {
      src: "/img/air/Chigo Split Air Conditioner 3.5kW-12000BTU-R-32.webp",
      responsive: "/img/air/Chigo Split Air Conditioner 3.5kW-12000BTU-R-32.webp",
      thumb: "/img/air/Chigo Split Air Conditioner 3.5kW-12000BTU-R-32.webp",
      alt: "Chigo Split Air Conditioner 3.5kW-12000BTU-R-32",
      description: "Chigo AC-12CHSD-W Inverter 3.5kw 12000Btu Wifi R32 GWP 675",
      price: "4999.99",
      subHtml: `...`,
    },
    {
      src: "/img/air/smart hyundai wall split air con 7000 btu.avif",
      responsive: "/img/air/smart hyundai wall split air con 7000 btu.avif",
      thumb: "/img/air/smart hyundai wall split air con 7000 btu.avif",
      alt: "Hyundai R32 T1 12000 Btu Air Condition",
      description: "High-Efficiency Cooling and Heating: The HYUNDAI R32 T1 12000 Btu Split Air Conditioner boasts an EER of 3.21 for cooling and COP of 3.61 for heating, ensuring efficient and cost-effective operation",
      price: "4999.99",
      subHtml: `...`,
    },
    {
      src: "/img/air/2.jpg",
      responsive: "/img/air/2.jpg",
      thumb: "/img/air/2.jpg",
      alt: "Air Conditioning Unit",
      description: "Commercial Grade Energy Efficient Split AC Systems",
      price: "2999.99",
      subHtml: `...`,
    },
    {
      src: "/img/Fertiliser.png",
      responsive: "/img/Fertiliser.png",
      thumb: "/img/Fertiliser.png",
      alt: "Fertiliser",
      description: "Various types of fertilisers",
      price: "2999.99",
      subHtml: `...`,
    },
    {
      src: "/img/PC/1.jpg",
      responsive: "/img/PC/1.jpg",
      thumb: "/img/PC/1.jpg",
      alt: "Hp Envy Laptops",
      description: "Hp Envy Business Laptops with various confifurations",
      price: "899.99",
      subHtml: `...`,
    },
    {
      src: "/img/PC/8.png",
      responsive: "/img/PC/8.png",
      thumb: "/img/PC/8.png",
      alt: "All I One Desktop PCs",
      description: "All I One Desktop PCs of various configurations",
      price: "2199.99",
      subHtml: `...`,
    },
    {
      src: "/img/PC/10.webp",
      responsive: "/img/PC/10.webp",
      thumb: "/img/PC/10.webp",
      alt: "Hp Laptops",
      description: "Hp Laptops of variuous configurations",
      price: "799.99",
      subHtml: `...`,
    },
    {
      src: "/img/PC/11.jpg",
      responsive: "/img/PC/11.jpg",
      thumb: "/img/PC/11.jpg",
      alt: "All-in-One PC",
      description: "27-inch All-in-One PC with Touch Screen",
      price: "1499.99",
      subHtml: `...`,
    },
    {
      src: "/img/PC/LOT7SUMIworkstations_precision_7820_gallery_2 (1).jpg",
      responsive: "/img/PC/LOT7SUMIworkstations_precision_7820_gallery_2 (1).jpg",
      thumb: "/img/PC/LOT7SUMIworkstations_precision_7820_gallery_2 (1).jpg",
      alt: "Dell Precision Workstation",
      description: "Dell Precision 7820 Workstation wit various configurations",
      price: "4599.99",
      subHtml: `...`,
    },
    {
      src: "/img/PC/GEN4.jpg",
      responsive: "/img/PC/GEN4.jpg",
      thumb: "/img/PC/GEN4.jpg",
      alt: "Lenovo Thinkpad X1 Carbon",
      description: "Lenovo Thinkpad X1 Carbon of various configurations",
      price: "1299.99",
      subHtml: `...`,
    },
    {
      src: "/img/PC/P340SSF.jpg",
      responsive: "/img/PC/P340SSF.jpg",
      thumb: "/img/PC/P340SSF.jpg",
      alt: "Lenovo Thinkstation Desktop PC",
      description: "Lenovo Thinkstation Desktop PC of various configurations",
      price: "1799.99",
      subHtml: `...`,
    },
    {
      src: "/img/PC/ktc-product-ssd-snv2s-500g-1-zm-lg.jpg",
      responsive: "/img/PC/ktc-product-ssd-snv2s-500g-1-zm-lg.jpg",
      thumb: "/img/PC/ktc-product-ssd-snv2s-500g-1-zm-lg.jpg",
      alt: "SSD Drive",
      description: "500GB NVMe SSD, Gen4 x4 Interface, Up to 7000MB/s",
      price: "89.99",
      subHtml: `...`,
    },
    {
      src: "/img/cctv/2C-1R.webp",
      responsive: "/img/cctv/2C-1R.webp",
      thumb: "/img/cctv/2C-1R.webp",
      alt: "2-Camera Kit",
      description: "2-Camera Security Kit with Recording Unit, Easy Setup",
      price: "449.99",
      subHtml: `...`,
    },
    {
      src: "/img/cctv/2.jpg",
      responsive: "/img/cctv/2.jpg",
      thumb: "/img/cctv/2.jpg",
      alt: "PTZ Camera",
      description: "Pan-Tilt-Zoom Camera with 30x Optical Zoom",
      price: "599.99",
      subHtml: `...`,
    },
    {
      src: "/img/cctv/6mp-hikvision-wdr-dome-ip-camera-1.webp",
      responsive: "/img/cctv/6mp-hikvision-wdr-dome-ip-camera-1.webp",
      thumb: "/img/cctv/6mp-hikvision-wdr-dome-ip-camera-1.webp",
      alt: "Hikvision Dome",
      description: "Hikvision 6MP WDR Dome IP Camera with IR",
      price: "249.99",
      subHtml: `...`,
    },
    {
      src: "/img/cctv/m3086v_ceiling_angle_left_2112_0.png.jpg",
      responsive: "/img/cctv/m3086v_ceiling_angle_left_2112_0.png.jpg",
      thumb: "/img/cctv/m3086v_ceiling_angle_left_2112_0.png.jpg",
      alt: "360° Camera",
      description: "360-Degree Panoramic Ceiling Camera",
      price: "499.99",
      subHtml: `...`,
    },
    {
      src: "/img/net/molex.webp",
      responsive: "/img/net/molex.webp",
      thumb: "/img/net/molex.webp",
      alt: "Network Cable",
      description: "Molex CAT6A Shielded Network Cable",
      price: "149.99",
      subHtml: `...`,
    },
    {
      src: "/img/net/1.jpg",
      responsive: "/img/net/1.jpg",
      thumb: "/img/net/1.jpg",
      alt: "Lenovo Thinksystem Rack Servers",
      description: "Lenovo Thinksystem Rack Servers with various configurationns",
      price: "1999.99",
      subHtml: `...`,
    },
    {
      src: "/img/net/s00006498.webp",
      responsive: "/img/net/s00006498.webp",
      thumb: "/img/net/s00006498.webp",
      alt: "HPE ProLiant DL380 Gen10 Server",
      description: "HPE ProLiant DL380 Gen10 Server with various configurations",
      price: "799.99",
      subHtml: `...`,
    },
    {
      src: "/img/net/dellemc-per550-16x2-5-above-lf-emc-honeycomb-bezel-w-lcd.png",
      responsive: "/img/net/dellemc-per550-16x2-5-above-lf-emc-honeycomb-bezel-w-lcd.png",
      thumb: "/img/net/dellemc-per550-16x2-5-above-lf-emc-honeycomb-bezel-w-lcd.png",
      alt: "Dell Server",
      description: "Dell PowerEdge R550 Rack Server",
      price: "4999.99",
      subHtml: `...`,
    },
    {
      src: "/img/net/71j51Xnm-lL.jpg",
      responsive: "/img/net/71j51Xnm-lL.jpg",
      thumb: "/img/net/71j51Xnm-lL.jpg",
      alt: "Aruba Network Switch",
      description: "Aruba Network switches of various configurations",
      price: "299.99",
      subHtml: `...`,
    },
    {
      src: "/img/net/1301_hi_res.png",
      responsive: "/img/net/1301_hi_res.png",
      thumb: "/img/net/1301_hi_res.png",
      alt: " MicroTik Ruter Switch",
      description: "MikroTik CRS326-24G-2S+RM (Cloud Router Switch) 24-Port Gigabit Router/Switch w/ 2 x SFP+ Ports (RouterOS/SwOS Level 5)",
      price: "189.99",
      subHtml: `...`,
    },
    {
      src: "/img/net/41ZC3n8QxDL.jpg",
      responsive: "/img/net/41ZC3n8QxDL.jpg",
      thumb: "/img/net/41ZC3n8QxDL.jpg",
      alt: "Ubiquiti Unifi Network Switches",
      description: "Ubiquiti Unifi Network Switches of different configurations",
      price: "149.99",
      subHtml: `...`,
    },
    {
      src: "/img/net/china kvm console.jpg",
      responsive: "/img/net/china kvm console.jpg",
      thumb: "/img/net/china kvm console.jpg",
      alt: "KVM Console",
      description: "1U Rack Mount KVM Console with 17\" LCD",
      price: "899.99",
      subHtml: `...`,
    },
    {
      src: "/img/bio/3.jpg",
      responsive: "/img/bio/3.jpg",
      thumb: "/img/bio/3.jpg",
      alt: "Biometric Access Control",
      description: "Biometric Access Control Devices",
      price: "799.99",
      subHtml: `...`,
    },
    {
      src: "/img/UPS/1.jpg",
      responsive: "/img/UPS/1.jpg",
      thumb: "/img/UPS/1.jpg",
      alt: "APC smart UPS",
      description: "APC smart UPS of various configurations",
      price: "399.99",
      subHtml: `...`,
    },
    {
      src: "/img/UPS/3.jpg",
      responsive: "/img/UPS/3.jpg",
      thumb: "/img/UPS/3.jpg",
      alt: "EATON Smart UPS",
      description: "EATON Smart UPS of various configurations",
      price: "899.99",
      subHtml: `...`,
    },
    {
      src: "/img/UPS/HRL1234WF2FR_product-1.jpg",
      responsive: "/img/UPS/HRL1234WF2FR_product-1.jpg",
      thumb: "/img/UPS/HRL1234WF2FR_product-1.jpg",
      alt: " UPS Battery",
      description: "UPS replacement batteries of various configurations",
      price: "89.99",
      subHtml: `...`,
    },
    {
      src: "/img/UPS/PSC-SOLAR-1.5KVA12V-OGM-HYBRID-SOLAR-INVERTER-1-1.webp",
      responsive: "/img/UPS/PSC-SOLAR-1.5KVA12V-OGM-HYBRID-SOLAR-INVERTER-1-1.webp",
      thumb: "/img/UPS/PSC-SOLAR-1.5KVA12V-OGM-HYBRID-SOLAR-INVERTER-1-1.webp",
      alt: "Solar Inverter",
      description: "1.5KVA Hybrid Solar Inverter",
      price: "799.99",
      subHtml: `...`,
    },
    {
      src: "/img/solar/lithium-battery.jpg",
      responsive: "/img/solar/lithium-battery.jpg",
      thumb: "/img/solar/lithium-battery.jpg",
      alt: "Lithium Battery",
      description: "48V 100Ah Lithium Battery for Solar Storage with MPP controller",
      price: "1499.99",
      subHtml: `...`,
    },
    {
      src: "/img/solar/lithium-ion-battery.webp",
      responsive: "/img/solar/lithium-ion-battery.webp",
      thumb: "/img/solar/lithium-ion-battery.webp",
      alt: "Li-ion Battery Pack",
      description: "Lithium-ion Battery Pack for Solar Systems",
      price: "1799.99",
      subHtml: `...`,
    },
    {
      src: "/img/solar/battery.png",
      responsive: "/img/solar/battery.png",
      thumb: "/img/solar/battery.png",
      alt: "Solar Battery",
      description: "Solar Energy Storage Battery System 10kWh",
      price: "3999.99",
      subHtml: `...`,
    },
    {
      src: "/img/solar/Photo-1.jpg",
      responsive: "/img/solar/Photo-1.jpg",
      thumb: "/img/solar/Photo-1.jpg",
      alt: "Solar Panel Irrigation systems",
      description: "High-Efficiency Solar Panel Irrigation systems",
      price: "399.99",
      subHtml: `...`,
    },
    {
      src: "/img/solar/solar-pump-new-hd.webp",
      responsive: "/img/solar/solar-pump-new-hd.webp",
      thumb: "/img/solar/solar-pump-new-hd.webp",
      alt: "Solar Pump",
      description: "Solar Powered Water Pump System",
      price: "899.99",
      subHtml: `...`,
    },
    {
      src: "/img/solar/solar-warer-pump-banner-mob.jpg",
      responsive: "/img/solar/solar-warer-pump-banner-mob.jpg",
      thumb: "/img/solar/solar-warer-pump-banner-mob.jpg",
      alt: "Solar Water Pump",
      description: "Complete Solar Water Pumping Solution with Controller",
      price: "1299.99",
      subHtml: `...`,
    }
  ];
  return <Gallery images={images} />;
};

export default page;
