import Gallery from "@/components/Gallery";
import React from "react";
import {ImageItem} from "../page";

//for now it only loads when all images are correct
//TODO make it load even if some pictures do not load
const page = () => {
      const images: ImageItem[] = [
    {
      src: "/img/Mapper_page0_image.png",
      responsive: "/img/Mapper_page0_image.png",
      thumb: "/img/Mapper_page0_image.png",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/G60F-GNSS-SPECS-800x800.png",
      responsive: "/img/G60F-GNSS-SPECS-800x800.png",
      thumb: "/img/G60F-GNSS-SPECS-800x800.png",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/PC/1.jpg",
      responsive: "/img/PC/1.jpg",
      thumb: "/img/PC/1.jpg",
      alt: "",
      subHtml: `...`,
    },
        {
      src: "/img/PC/8.png",
      responsive: "/img/PC/8.png",
      thumb: "/img/PC/8.png",
      alt: "",
      subHtml: `...`,
    },
        {
      src: "/img/PC/10.webp",
      responsive: "/img/PC/10.webp",
      thumb: "/img/PC/10.webp",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/PC/3.jpg",
      responsive: "/img/PC/3.jpg",
      thumb: "/img/PC/3.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/PC/11.jpg",
      responsive: "/img/PC/11.jpg",
      thumb: "/img/PC/11.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/PC/LOT7SUMIworkstations_precision_7820_gallery_2 (1).jpg",
      responsive: "/img/PC/LOT7SUMIworkstations_precision_7820_gallery_2 (1).jpg",
      thumb: "/img/PC/LOT7SUMIworkstations_precision_7820_gallery_2 (1).jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/PC/GEN4.jpg",
      responsive: "/img/PC/GEN4.jpg",
      thumb: "/img/PC/GEN4.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/PC/P340SSF.jpg",
      responsive: "/img/PC/P340SSF.jpg",
      thumb: "/img/PC/P340SSF.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/cctv/5.webp",
      responsive: "/img/cctv/5.webp",
      thumb: "/img/cctv/5.webp",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/cctv/3.png",
      responsive: "/img/cctv/3.png",
      thumb: "/img/cctv/3.png",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/cctv/2C-1R.webp",
      responsive: "/img/cctv/2C-1R.webp",
      thumb: "/img/cctv/2C-1R.webp",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/cctv/2.jpg",
      responsive: "/img/cctv/2.jpg",
      thumb: "/img/cctv/2.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/cctv/6mp-hikvision-wdr-dome-ip-camera-1.webp",
      responsive: "/img/cctv/6mp-hikvision-wdr-dome-ip-camera-1.webp",
      thumb: "/img/cctv/6mp-hikvision-wdr-dome-ip-camera-1.webp",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/cctv/DS-2CD2163G0-IS-2.8MM.jpg",
      responsive: "/img/cctv/DS-2CD2163G0-IS-2.8MM.jpg",
      thumb: "/img/cctv/DS-2CD2163G0-IS-2.8MM.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/cctv/bec178fb-a87b-482e-a855-bec0195dc03c.jpg",
      responsive: "/img/cctv/bec178fb-a87b-482e-a855-bec0195dc03c.jpg",
      thumb: "/img/cctv/bec178fb-a87b-482e-a855-bec0195dc03c.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/cctv/m3086v_ceiling_angle_left_2112_0.png.jpg",
      responsive: "/img/cctv/m3086v_ceiling_angle_left_2112_0.png.jpg",
      thumb: "/img/cctv/m3086v_ceiling_angle_left_2112_0.png.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/net/6.jpg",
      responsive: "/img/net/6.jpg",
      thumb: "/img/net/6.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/net/molex.webp",
      responsive: "/img/net/molex.webp",
      thumb: "/img/net/molex.webp",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/net/9.webp",
      responsive: "/img/net/9.webp",
      thumb: "/img/net/9.webp",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/net/1.jpg",
      responsive: "/img/net/1.jpg",
      thumb: "/img/net/1.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/net/s00006498.webp",
      responsive: "/img/net/s00006498.webp",
      thumb: "/img/net/s00006498.webp",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/net/cisco.webp",
      responsive: "/img/net/cisco.webp",
      thumb: "/img/net/cisco.webp",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/net/dellemc-per550-16x2-5-above-lf-emc-honeycomb-bezel-w-lcd.png",
      responsive: "/img/net/dellemc-per550-16x2-5-above-lf-emc-honeycomb-bezel-w-lcd.png",
      thumb: "/img/net/dellemc-per550-16x2-5-above-lf-emc-honeycomb-bezel-w-lcd.png",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/net/71j51Xnm-lL.jpg",
      responsive: "/img/net/71j51Xnm-lL.jpg",
      thumb: "/img/net/71j51Xnm-lL.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/net/1301_hi_res.png",
      responsive: "/img/net/1301_hi_res.png",
      thumb: "/img/net/1301_hi_res.png",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/net/41ZC3n8QxDL.jpg",
      responsive: "/img/net/41ZC3n8QxDL.jpg",
      thumb: "/img/net/41ZC3n8QxDL.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/air/1.webp",
      responsive: "/img/air/1.webp",
      thumb: "/img/air/1.webp",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/air/2.jpg",
      responsive: "/img/air/2.jpg",
      thumb: "/img/air/2.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/bio/1.webp",
      responsive: "/img/bio/1.webp",
      thumb: "/img/bio/1.webp",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/bio/3.jpg",
      responsive: "/img/bio/3.jpg",
      thumb: "/img/bio/3.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/PC/7.webp",
      responsive: "/img/PC/7.webp",
      thumb: "/img/PC/7.webp",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/UPS/1.jpg",
      responsive: "/img/UPS/1.jpg",
      thumb: "/img/UPS/1.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/UPS/3.jpg",
      responsive: "/img/UPS/3.jpg",
      thumb: "/img/UPS/3.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/UPS/4.jpg",
      responsive: "/img/UPS/4.jpg",
      thumb: "/img/UPS/4.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/UPS/HRL1234WF2FR_product-1.jpg",
      responsive: "/img/UPS/HRL1234WF2FR_product-1.jpg",
      thumb: "/img/UPS/HRL1234WF2FR_product-1.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/UPS/PSC-SOLAR-1.5KVA12V-OGM-HYBRID-SOLAR-INVERTER-1-1.webp",
      responsive: "/img/UPS/PSC-SOLAR-1.5KVA12V-OGM-HYBRID-SOLAR-INVERTER-1-1.webp",
      thumb: "/img/UPS/PSC-SOLAR-1.5KVA12V-OGM-HYBRID-SOLAR-INVERTER-1-1.webp",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/solar/lithium-battery.jpg",
      responsive: "/img/solar/lithium-battery.jpg",
      thumb: "/img/solar/lithium-battery.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/solar/lithium-ion-battery.webp",
      responsive: "/img/solar/lithium-ion-battery.webp",
      thumb: "/img/solar/lithium-ion-battery.webp",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/solar/battery.png",
      responsive: "/img/solar/battery.png",
      thumb: "/img/solar/battery.png",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/solar/solar-lifepo4-lithium-battery.jpg",
      responsive: "/img/solar/solar-lifepo4-lithium-battery.jpg",
      thumb: "/img/solar/solar-lifepo4-lithium-battery.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/solar/Photo-1.jpg",
      responsive: "/img/solar/Photo-1.jpg",
      thumb: "/img/solar/Photo-1.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/solar/solar-pump-new-hd.webp",
      responsive: "/img/solar/solar-pump-new-hd.webp",
      thumb: "/img/solar/solar-pump-new-hd.webp",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/solar/solar-warer-pump-banner-mob.jpg",
      responsive: "/img/solar/solar-warer-pump-banner-mob.jpg",
      thumb: "/img/solar/solar-warer-pump-banner-mob.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/net/KVM1.jpg",
      responsive: "/img/net/KVM1.jpg",
      thumb: "/img/net/KVM1.jpg",
      alt: "",
      subHtml: `...`,
    },
    {
      src: "/img/net/china kvm console.jpg",
      responsive: "/img/net/china kvm console.jpg",
      thumb: "/img/net/china kvm console.jpg",
      alt: "",
      subHtml: `...`,
    },
        {
      src: "/img/PC/ktc-product-ssd-snv2s-500g-1-zm-lg.jpg",
      responsive: "/img/PC/ktc-product-ssd-snv2s-500g-1-zm-lg.jpg",
      thumb: "/img/PC/ktc-product-ssd-snv2s-500g-1-zm-lg.jpg",
      alt: "",
      subHtml: `...`,
    }
];
  return <Gallery images={images} />;
};

export default page;
